### ISSUE TITLE
Building from scratch generates errors

### ISSUE THREAD

**Issue by gpeel** [observable-playground/observable-playground#40]
after npm i
npm build, 

I got the following logs.
What am doing wrong ?
```

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=   ] info  - Generating static pages (0/80)⚡️ @20:06:40
⚡️ @20:06:40
⚡️ @20:06:40
⚡️ @20:06:40
⚡️ @20:06:41
[=== ] info  - Generating static pages (0/80)
Error occurred prerendering page "/rxjs/concatMap". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading '2')
    at getStaticProps (C:\me\JS\RxJS\OBSERVABLE-PLAYGROUND\.next\server\pages\[libId]\[fileId].js:291:36)
    at renderToHTML (C:\me\JS\RxJS\OBSERVABLE-PLAYGROUND\node_modules\next\dist\next-server\server\render.js:27:1786)
    at async C:\me\JS\RxJS\OBSERVABLE-PLAYGROUND\node_modules\next\dist\export\worker.js:26:6
    at async Span.traceAsyncFn (C:\me\JS\RxJS\OBSERVABLE-PLAYGROUND\node_modules\next\dist\telemetry\trace\trace.js:6:584)
```

and many more similar errors.

**Comment by kosich** [comment]
Hey, @gpeel! :wave:

Sorry for the late response. I think this is due to how I was parsing meta information from `.md` files. I wrongly assumed only `\n` line endings.

I just pushed a change that should fix it: https://github.com/observable-playground/observable-playground/commit/5b4c320e50f53daaf0654538565663fadd0fc272 . Could you pull the latest `master` and try again?
